name: Build and Release

on:
  push:
    tags:
      - 'v*' # Triggers when you push a tag like v0.1
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSVC (Visual Studio Build Tools)
        uses: ilammy/msvc-dev-cmd@v1

      - name: Run Build Script
        shell: cmd
        run: |
          call build.bat

      - name: Create Release and Upload
        uses: softprops/action-gh-release@v2
        with:
          files: clicker.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
